# Generated by Django 3.2 on 2023-01-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='pantry_id',
            new_name='pantry',
        ),
        migrations.RenameField(
            model_name='pantry',
            old_name='user_id',
            new_name='user',
        ),
    ]
